---

- name: Installing kubernetes yum repo
  template:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    mode: u=rw,g=r,o=r

- name: Copying script to disable SELinux
  template:
    src: disable_se.sh
    dest: /opt/disable_se.sh
    mode: u=rw,g=r

- name: Disabling SELinux
  command: /bin/bash /opt/disable_se.sh

- name: Installing kubernetes packages
  yum:
    name: "{{ k8_pkg }}"
    state: present

- name: Enabling kubelet service
  systemd:
    name: kubelet
    enabled: yes
    state: started

- name: Configuring iptables for kubernetes
  template:
    src: k8s.conf
    dest: /etc/sysctl.d/k8s.conf

- name: Applying sysctl config
  command: sysctl --system

- name: Copying script to create k8 cluster
  template: 
    src: create_cluster.sh
    dest: /opt/create_cluster.sh
    mode: u=rw,g=r,o=r

- name: Configuring kubernetes cluster
  command: /bin/bash /opt/create_cluster.sh
  become_user: vagrant

- name: Copying python script to list running pods
  template:
    src: pods.py
    dest: /home/vagrant/pods.py
    mode: u=rw
    owner: vagrant
    group: vagrant
